apiVersion: v1
kind: Service
metadata:
 name: patient-service
spec:
  type: NodePort
  selector:
    app: patient-app
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 3000  
      nodePort: 30007  